class_name LevelCatalog
extends RefCounted
## Level catalog — parses assets/levels/levels.json (generated by
## 33_export_levels.py) and runner.yaml. Pure data access, no scene logic.

const CATALOG_PATH := "res://assets/levels/levels.json"
const RUNNER_PATH := "res://assets/levels/runner.yaml"

var schools: Array = []
var episodes: Array = []
var levels: Dictionary = {}


func load_catalog() -> bool:
	var f := FileAccess.open(CATALOG_PATH, FileAccess.READ)
	if f == null:
		push_warning("level_catalog: missing %s" % CATALOG_PATH)
		return false
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		push_warning("level_catalog: bad JSON in %s" % CATALOG_PATH)
		return false
	schools = parsed.get("schools", [])
	episodes = parsed.get("episodes", [])
	levels = parsed.get("levels", {})
	return true


func get_groups(mode: String) -> Array:
	return schools if mode == "schools" else episodes


func get_level(code: String) -> Dictionary:
	return levels.get(code, {})


func display_name(code: String) -> String:
	var lv := get_level(code)
	if lv.is_empty():
		return code
	var name: String = lv.get("name", code)
	if lv.has("name_en"):
		name += " / " + str(lv["name_en"])
	return "%s (%s)" % [name, code]


func is_available(code: String) -> bool:
	if not ResourceLoader.exists("res://scenes/maps/%s.tscn" % code):
		return false
	return DirAccess.dir_exists_absolute(
		ProjectSettings.globalize_path("res://assets/maps/%s" % code))


func load_runner_config() -> Dictionary:
	# Flat "key: value" YAML (comments/# and blank lines skipped) —
	# same mini-parser approach as the avatar tool's monsters.yaml reader.
	var out := {}
	var f := FileAccess.open(RUNNER_PATH, FileAccess.READ)
	if f == null:
		return out
	while not f.eof_reached():
		var line := f.get_line().strip_edges()
		if line.is_empty() or line.begins_with("#") or not line.contains(":"):
			continue
		var key := line.get_slice(":", 0).strip_edges()
		var val := line.substr(line.find(":") + 1).strip_edges()
		out[key] = float(val) if val.is_valid_float() else val
	return out
